create table attendants (
    id bigint generated by default as identity primary key,
    name varchar(150) not null,
    team varchar(20) not null,
    active boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint chk_attendants_team
        check (team in ('CARDS', 'LOANS', 'OTHERS'))
);

create table attendances (
    id bigint generated by default as identity primary key,
    customer_name varchar(150) not null,
    message varchar(500) not null,
    subject varchar(30) not null,
    team varchar(20) not null,
    status varchar(20) not null,
    attendant_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    constraint chk_attendances_subject
        check (subject in ('CARD_PROBLEM', 'LOAN_REQUEST', 'OTHER')),
    constraint chk_attendances_team
        check (team in ('CARDS', 'LOANS', 'OTHERS')),
    constraint chk_attendances_status
        check (status in ('WAITING', 'IN_PROGRESS', 'FINISHED')),
    constraint chk_attendances_finished_requires_started
        check (finished_at is null or started_at is not null),
    constraint chk_attendances_finished_after_started
        check (finished_at is null or finished_at >= started_at),
    constraint fk_attendance_attendant
        foreign key (attendant_id)
        references attendants (id)
);

create index idx_attendants_team_active on attendants (team, active);
create index idx_attendances_team_status_created_at on attendances (team, status, created_at);
